export const vocabularyGroups = [
  {
    id: 'people',
    title: 'People & names',
    japaneseTitle: '人・名前',
    words: [
      ['わたし', 'watashi', 'I; neutral and polite, used by all genders'],
      ['あたし', 'atashi', 'I; casual and feminine-coded, mostly used in speech'],
      ['僕', 'boku', 'I; commonly used by boys and men, with a softer tone than 俺'],
      ['わたしたち', 'watashitachi', 'we; us'],
      ['あなた', 'anata', 'you (often omitted in conversation)'],
      ['彼', 'kare', 'he; sometimes boyfriend'],
      ['彼女', 'kanojo', 'she; sometimes girlfriend'],
      ['あの人', 'ano hito', 'that person'],
      ['あの方', 'ano kata', 'that person (polite)'],
      ['みなさん', 'minasan', 'everyone'],
      ['だれ／どなた', 'dare / donata', 'who / who (polite)'],
      ['〜さん', '〜san', 'polite name suffix for others'],
      ['〜ちゃん／〜くん', '〜chan / 〜kun', 'familiar suffixes; use when appropriate to the relationship'],
    ],
  },
  {
    id: 'identity',
    title: 'Work & identity',
    japaneseTitle: '仕事・身分',
    words: [
      ['〜人', '〜jin', 'nationality suffix'],
      ['先生／教師', 'sensei / kyōshi', 'teacher; 先生 is a respectful title, 教師 is the profession'],
      ['学生', 'gakusei', 'student'],
      ['会社員／社員', 'kaishain / shain', 'company employee / employee of a particular company'],
      ['銀行員', 'ginkōin', 'bank employee'],
      ['医者', 'isha', 'doctor'],
      ['技師', 'gishi', 'technician / technologist; often a specialist title in healthcare'],
      ['研究者', 'kenkyūsha', 'researcher'],
      ['エンジニア', 'enjinia', 'engineer'],
      ['大学', 'daigaku', 'university'],
      ['病院', 'byōin', 'hospital'],
    ],
  },
  {
    id: 'origins',
    title: 'Countries & origins',
    japaneseTitle: '国・出身',
    words: [
      ['〜から来ました', '〜kara kimashita', 'I came from ~'],
      ['アメリカ', 'Amerika', 'the United States'],
      ['イギリス', 'Igirisu', 'the United Kingdom'],
      ['インド', 'Indo', 'India'],
      ['インドネシア', 'Indoneshia', 'Indonesia'],
      ['韓国', 'Kankoku', 'South Korea'],
      ['タイ', 'Tai', 'Thailand'],
      ['中国', 'Chūgoku', 'China'],
      ['ドイツ', 'Doitsu', 'Germany'],
      ['日本', 'Nihon', 'Japan'],
      ['ブラジル', 'Burajiru', 'Brazil'],
      ['ベトナム', 'Betonamu', 'Vietnam'],
      ['ベトナム人', 'Betonamujin', 'Vietnamese person'],
    ],
  },
  {
    id: 'age-and-replies',
    title: 'Age & replies',
    japaneseTitle: '年齢・返事',
    words: [
      ['〜歳', '〜sai', 'years old'],
      ['何歳／おいくつ', 'nansai / oikutsu', 'how old? / how old? (polite)'],
      ['はい', 'hai', 'yes'],
      ['いいえ', 'iie', 'no'],
      ['そうです', 'sō desu', 'that’s right; confirms what was said'],
      ['違います', 'chigaimasu', 'that’s not right; politely corrects what was said'],
    ],
  },
  {
    id: 'meeting-phrases',
    title: 'First-meeting phrases',
    japaneseTitle: '出会いの表現',
    words: [
      ['はじめまして', 'hajimemashite', 'Nice to meet you (first meeting)'],
      ['どうぞよろしくお願いします', 'dōzo yoroshiku onegaishimasu', 'Pleased to meet you'],
      ['こちらこそ', 'kochira koso', 'Likewise; a polite reply to よろしくお願いします'],
      ['失礼ですが', 'shitsurei desu ga', 'Excuse me, but…'],
      ['お名前は？', 'onamae wa?', 'And your name? (polite, but direct)'],
      ['こちらは〜さんです', 'kochira wa ~san desu', 'This is [name]-san'],
    ],
  },
] as const;

export const vocabularySections = [
  ['people', 'People & names'],
  ['identity', 'Work & identity'],
  ['origins', 'Countries & origins'],
  ['age-and-replies', 'Age & replies'],
  ['meeting-phrases', 'First-meeting phrases'],
  ['usage-notes', 'Usage notes'],
] as const;
